### ISSUE TITLE
New audio sources

### ISSUE THREAD

**Issue by TylerFisher** [NUKnightLab/soundcite#12]
Explore YouTube, Vimeo APIs for video-based audio.

**Comment by walker** [comment]
Separating (and playing) the audio directly from the YouTube api/service would be a violation of their [term](https://developers.google.com/youtube/terms) (section II, number 8).

**Comment by walker** [comment]
I checked out the Vimeo API and they don't have any information that supplies audio-only files, and their [API Terms](https://developer.vimeo.com/guidelines/terms#license_restrictions_advanced) seem to preclude this usage there, as well (section 2.2.4).

**Comment by scott2b** [comment]
to be clear. YouTube: Prohibitions include "separate, isolate, or modify the audio or video components of any YouTube audiovisual content made available through the YouTube API;" and Vimeo: "You will not alter, remove, replace, or mask any aspect of the Vimeo Player (including the playbar, logo, and like, embed, and share features) without Vimeo’s prior written consent." I would take "masking" to include the blocking of video only to include audio.

Thanks for digging into this @walker. This feature is not really on any development roadmap at the moment. I am closing this based on this bit of helpful sleuthing. Thank you!
