### ISSUE TITLE
Some CMSes will strip out data attributes

### ISSUE THREAD

**Issue by TylerFisher** [NUKnightLab/soundcite#28]
Such as WordPress, depending on your user status. This is a pretty crippling problem, I imagine.

**Comment by scott2b** [comment]
As SoundCite operates as an embed code, managing HTML sanitization for CMSes (generalized) really seems out of scope of what we can reasonably address. I don't really see this as a bug. Prefer to close this as wontfix. Comments before I do @JoeGermuska ?

**Comment by JoeGermuska** [comment]
I agree that this is **wontfix**. 

Abstractly, we could have markup which writes a data file somewhere (like S3) and then only use id attributes in the actual markup we specify, but that all seems like just trading for a different kind of complication.
