### ISSUE TITLE
JS error when loading soundcite

### ISSUE THREAD

**Issue by cherihung** [NUKnightLab/soundcite#30]
Hi, I am all of a sudden experiencing a problem playing soundcite clips in a project I'm building now. They won't play. They were working a day ago.

More importantly, I am also seeing the same exact error on Soundcite's homepage.
(I had two other people on my team test Soundcite's homepage. And tested on several different machines too.  All experiencing the problem.)

console error (in Firefox and chrome)

GET http://connect.soundcloud.com/audiomanager/audiomanager.js 404 (Not Found) sdk.js:1
GET https://api.soundcloud.com/tracks/1848538?client_id=0f8fdbbaa21a9bd18210986a7dc2d72c&format=json 404 (Not Found) 

Occasionally I also see a Uncaught Type Error [object object] not found

**Comment by jywsn** [comment]
This should no longer be an issue.
