### ISSUE TITLE
Wordpress plugin

### ISSUE THREAD

**Issue by wfsmith** [NUKnightLab/soundcite#31]
Hi guys.  I have written a basic Wordpress plugin for SoundCite. 

You can find it here:  https://github.com/wfsmith/soundcite-wordpress

It uses a TinyMCE dialog to first resolve the public soundcloud url to a track id, and then embeds it as a shortcode.   The shortcode is then converted back to the necessary markup to make soundcite work.

This is my first public git repo, and my first public wordpress plugin (I've written many that we use internally), so please let me know if any issues/bugs or anything I can do to improve it.

**Comment by scott2b** [comment]
I appreciate efforts here from @wfsmith. Would like, however, to get this out of our issues list. @JoeGermuska can you clarify why this is marked as enhancement? What is the task here?
