### ISSUE TITLE
Soundcloud.js and Popcorn.js loaded even if not needed

### ISSUE THREAD

**Issue by rdmurphy** [NUKnightLab/soundcite#36]
Hey folks! This was a recent blocker for us with `soundcite`. We were going the `mp3` route with a project and I noticed these two libs were getting pulled in even though we didn't need them. (Full disclosure – only assuming we wouldn't have needed `Popcorn.js`. But I know Soundcloud wasn't.) I noticed jQuery getting pulled in as well even though we already had it on the page.

I understand that this is meant to be a drop-in-and-forget-it solution, but it would be awesome to have a version of this that places the onus on the developer to ensure the dependencies are met. For example, our [app template](https://github.com/texastribune/newsapps-app-template) has the ability to compile all our assets into one file for production. If we knew soundcloud.js and popcorn.js would be needed, we could manage that and let those be compressed by our asset pipeline.

What do y'all think?

**Comment by ThomasHelzle** [comment]
I'm in a similar situation - I have jquery already on my pages and don't use soundcloud but local mp3s - how do I prevent those from being pulled in? How was this solved? (Sorry, my code-reading isn't the best ;-) ).

**Comment by JoeGermuska** [comment]
@ThomasHelzle I see you're saying that you would prefer that soundcite not load the Soundcloud SDK if you're only using MP3s? This is kind of complicated, but I think we could do it.

**Comment by ThomasHelzle** [comment]
Thanks Joe, that would be great. 
If automatic detection is too complicated, I would be fine with a manual flag/option.
I found in the meantime that auto-detection indeed works if I load popcorn and jquery locally from my server on the page before soundcite, but in the case of soundcloud I don't see myself ever using it for soundcite.

**Comment by JoeGermuska** [comment]
fixed in 43b8c37166e3693c3fce0cdda710a05706ba7651

**Comment by ThomasHelzle** [comment]
Super. Makes a lot of sense and loads much faster now. Gracias :-)
