### ISSUE TITLE
Allow to omit data-start and data-end

### ISSUE THREAD

**Issue by ThomasHelzle** [NUKnightLab/soundcite#38]
I currently test soundcite for playing local audio pieces and thought it would make a lot of sense to be able to omit data-start and data-end in cases where you already have the snippets prepared beforehand in the right length:
- Leaving out data-start would play from start.
- Leaving out data-end would play until the end.

Thanks!

Tom

**Comment by lukerague** [comment]
Added as of ad523184a93f717b065661340da55c032f6a1383

**Comment by ThomasHelzle** [comment]
Cool, thanks a lot!
I'll give it a go right away.

**Comment by JoeGermuska** [comment]
Note that this has not yet been deployed to our CDN...

**Comment by ThomasHelzle** [comment]
I use your github repo version locally, I don't like CDNs :-)
Thanks, works great and makes soundcite much more logical and streamlined IMO.
