### ISSUE TITLE
Allow to loop audio

### ISSUE THREAD

**Issue by ThomasHelzle** [NUKnightLab/soundcite#39]
In some cases it would be interesting to be able to loop the audio - I had several ideas on this:
- If I enter a data-end position that is longer than the actual clip, loop it for the remaining time.
- Have an optional data-loop parameter that loops:
  - When it's set to 0, it loops infinitely.
  - When it's set to any higher number, it loops that number of times.
This would allow to use shorter audio clips in some cases.

Thanks,

Tom

**Comment by lukerague** [comment]
Added as of 9dd0153729ad0b11c82d73431239d2cb217b9a7b

**Comment by ThomasHelzle** [comment]
Thanks a lot lukerague!

**Comment by ThomasHelzle** [comment]
Looping as such works. 
Cool.

Problems:
- If I don't set a start and end point, and set data-plays="4", the loop runs endless.

- Not sure if that can be solved by soundcite: I get clicks and a short interruption on each loop. The same soundfile loops smoothly for instance with http://mediaelementjs.com/

Cheers,

Tom
