### ISSUE TITLE
Allow multiple audio snippets running at the same time as an option.

### ISSUE THREAD

**Issue by ThomasHelzle** [NUKnightLab/soundcite#40]
I am thinking about using soundcite for a kind of interactive story with some sounddesign elements that I would love to allow the user to let keep running in the background. For this it would be great to have an option/a flag that could be set for specific clips so that they are no truncated when another clip is started (if that is possible).

Thanks!

Tom

**Comment by JoeGermuska** [comment]
I think we'll pass on this one. It's really quite counter to the design intention for Soundcite.

To implement something like this, look at the documentation for javascript libraries like [PopcornJS](http://popcornjs.org/) or [SoundManager2](http://www.schillmania.com/projects/soundmanager2/).
