### ISSUE TITLE
Popcorn JS not using protocol-relative URL

### ISSUE THREAD

**Issue by paulschreiber** [NUKnightLab/soundcite#51]
You're loading popcorn over `http` instead of using a protocol-relative URL:
```js
var script = document.createElement("script");
script.type = "text/javascript";
script.src = "http://cdn.knightlab.com/libs/soundcite/latest/vendor/popcorn.min.js"; // no SSL version of this, will self-host
```

* Change this to `script.src = "//cdn.knightlab.com/libs/soundcite/latest/vendor/popcorn.min.js";`
* Fix cdn.knightlab.com so it supports https

**Comment by jywsn** [comment]
Fixed in 0.4.1
