### ISSUE TITLE
docs use protocol-relative URLs, but cdn.knightlab.com doesn't support HTTPS

### ISSUE THREAD

**Issue by paulschreiber** [NUKnightLab/soundcite#52]
On soundcite.knightlab.com, this copy-and-paste code is provided:

    <link href='//cdn.knightlab.com/libs/soundcite/latest/css/player.css' rel='stylesheet' type='text/css'>
    <script type='text/javascript' src='//cdn.knightlab.com/libs/soundcite/latest/js/soundcite.min.js'></script>

However, cdn.knightlab.com doesn't support HTTPS, so this won't work on secure sites.

Suggested fixes
* set up a CloudFront distribution with your S3 bucket as its origin (preferred, since this will be an actual CDN), or,
* use the S3 https URLs:
  * //s3.amazonaws.com/cdn.knightlab.com/libs/soundcite/latest/css/player.css
  * //s3.amazonaws.com/cdn.knightlab.com/libs/soundcite/latest/js/soundcite.min.js

Note that for this to work, you'll also have to fix #51, so that:
```js
script.src = "http://cdn.knightlab.com/libs/soundcite/latest/vendor/popcorn.min.js"; // no SSL version of this, will self-host
```

gets replaced with a protocol-relative URL.

**Comment by jywsn** [comment]
Fixed in 0.4.1
