### ISSUE TITLE
if one instance of markup on page is malformed, then all others following it will fail to load

### ISSUE THREAD

**Issue by montchr** [NUKnightLab/soundcite#55]
If I paste an embed code into my CMS' editor, the data attributes are stripped out — this is well documented and understandable. Resulted in markup like `<span class="soundcite">text</span>`. This fails with the error:

```
sdk-2.0.0.js:2 Uncaught TypeError: Cannot read property 'toString' of null

window.SC.SC.Helper.merge._isNumeric @ sdk-2.0.0.js:2
window.SC.SC.Helper.merge._prepareTrackUrl @ sdk-2.0.0.js:2
window.SC.SC.Helper.merge.stream @ sdk-2.0.0.js:2
SoundCloudClip @ soundcite.min.js?ver=4.4.2:4
(anonymous function) @ soundcite.min.js?ver=4.4.2:4
(anonymous function) @ soundcite.min.js?ver=4.4.2:4
script.onload.script.onreadystatechange @ soundcite.min.js?ver=4.4.2:4
```

However, in my tests, I left this failed attempt in my article's markup. Because this malformed markup still existed, the script would fail upon discovering it, and would not continue on to process all of the valid instances of the markup further down the page.

I would expect the script to fail gracefully, throw a helpful error message into the console, and continue on through the document to process the remaining valid instances of SoundCite markup.

**Comment by JoeGermuska** [comment]
relates to #28

**Comment by montchr** [comment]
Great, thanks!
