### ISSUE TITLE
User configurable Soundcloud API key

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/soundcite#59]
It seems that Soundcloud's new more restrictive API rules mean that occasionally the global pool of SoundCite installations maxes out the number of plays permitted for the single shared API key which comes configured in SoundCite.

SoundCite was adapted to support users configuring their own API key. Instructions are below. We should figure out a way to integrate this into the web user interface without overcomplicating things.

<hr>
If you want to make sure that your SoundCite installation is not hindered by the popularity of anyone else's SoundCite installation, you should create your own Soundcloud "app" and then add some configuration to your page.

### Creating a Soundcloud app

Go to the [Your Applications](http://soundcloud.com/you/apps) page and click on "register a new application".  Choose any name you like and check the little checkbox. On the next page, copy the "client ID". You can ignore everything else on the page.

### Configuring SoundCite with your Client ID

```html
<script type="text/javascript">
SOUNDCITE_CONFIG = {
    soundcloud_client_id: "your_client_id_here"
}
</script>
<!-- the above should go in your page before this boilerplate which comes from step 3 of the "make a clip" interface -->
<link href='https://cdn.knightlab.com/libs/soundcite/latest/css/player.css' 
      rel='stylesheet' 
      type='text/css'>
<script type='text/javascript' 
        src='https://cdn.knightlab.com/libs/soundcite/latest/js/soundcite.min.js'></script>
```

**Comment by scott2b** [comment]
There is now an optional box to paste an API key before copying the embed code. Instructions similar to above are also included as a help overlay for this input, as well as in a new FAQ entry.
