### ISSUE TITLE
Android Bug

### ISSUE THREAD

**Issue by jmccraw** [NUKnightLab/soundcite#64]
Sometimes when using Chrome on Android, an MP3 audio clip will trigger the `track_progress` event on `stop` because it seems to activate both the vanilla (`Clip.prototype.stop`) version of the event and the Popcorn check (`this.stop(); this.sound.currentTime(this.start);`). This forces it to loop endlessly. Doesn't seem to happen on desktop.

**Comment by yawkity** [comment]
Hi @jmccraw, Do you have any update or example for us to test this with? Is this still an issue you're facing?

**Comment by jmccraw** [comment]
I don't remember the original location for this bug. But testing a few articles, I can't reproduce it. Must have been fixed with a Chrome update.
