### ISSUE TITLE
Certain Soundcloud links not working

### ISSUE THREAD

**Issue by thehandsomepanther** [NUKnightLab/soundcite#65]
Some Soundcloud links are throwing 403 errors, which are causing Soundcite to break. This might be cause by new Soundcloud track share settings, but more investigation is needed. At the very least this error should be captured when encountered and the issue should be documented somewhere.

**Comment by thehandsomepanther** [comment]
after doing a little digging, I believe this may be related to Soundcloud's new service, [Soundcloud Go ](https://blog.soundcloud.com/2016/03/29/introducing-soundcloud-go/)

**Comment by JoeGermuska** [comment]
This is happening with our long-standing example, [Tame Impala's Elephant.](https://soundcloud.com/tame-impala/elephant)  (The version in the 'ways you can use - music' section comes from an MP3)

I replaced that as an example in the "make clip interface" but we should still look for a way to catch the error.

**Comment by jeancochrane** [comment]
I'm experiencing this right now with 404 errors, which wind up blocking script execution on the page. Would be happy to take a stab at a PR if that would be helpful!

**Comment by JoeGermuska** [comment]
In general, we'd be happy to entertain PRs for Soundcite -- but we've had to acknowledge that SoundCloud is not a good hosting option for the tool. Now that SoundCloud no longer issues API credentials, most people who would use SoundCloud could not expect reliable playability because the "default" key in the distribution has its daily quota maxed out much of the time.

**Comment by jeancochrane** [comment]
That's good to know, thanks @JoeGermuska! I think we'll explore alternative hosting options instead of dedicating our time to fixing SoundCloud, then.

**Comment by JoeGermuska** [comment]
cleaning out the open issues.  Since Soundcloud doesn't issue APIs and we discourage new Soundcite projects using Soundcloud, closing this as WONTFIX
