### ISSUE TITLE
Better documentation for using a custom API key

### ISSUE THREAD

**Issue by scott2b** [NUKnightLab/soundcite#67]
We should have a more complete, screenshotted tutorial for obtaining a SoundCloud API key and using it with the editor (optional box in step 3) or **updating an existing deployment with the obtained key**.

Step 3 in the editor currently takes an optional API key. This box has a clickable `?` help overlay with steps to obtain a key for pasting into the box. There should also be a link in this overlay to a more complete tutorial. Tutorial should also be accessible via standard help navigation

**Comment by yawkity** [comment]
Screenshotted images for first part of process:

<img width="1280" alt="screen shot 2017-01-24 at 4 08 56 pm" src="https://cloud.githubusercontent.com/assets/3255833/22269482/26d38154-e251-11e6-91cb-e33f7ba2625c.png">
<img width="1280" alt="screen shot 2017-01-24 at 4 09 36 pm" src="https://cloud.githubusercontent.com/assets/3255833/22269485/29686b8c-e251-11e6-86df-9f7c83166a84.png">
<img width="1280" alt="screen shot 2017-01-24 at 4 12 17 pm" src="https://cloud.githubusercontent.com/assets/3255833/22269487/2bdc55c2-e251-11e6-9ee3-d2f712e642de.png">

**Comment by yawkity** [comment]
After 2 weeks finally got approved to move forward

**Comment by yawkity** [comment]
<img width="725" alt="screen shot 2017-02-08 at 3 17 15 pm" src="https://cloud.githubusercontent.com/assets/3255833/22758121/f2fa5ace-ee12-11e6-8f34-df0002d58f15.png">
<img width="830" alt="screen shot 2017-02-08 at 3 18 09 pm" src="https://cloud.githubusercontent.com/assets/3255833/22758127/f66ca298-ee12-11e6-970e-ed28f768a2b3.png">

**Comment by JoeGermuska** [comment]
cleaning out the open issues.  Since SoundCloud no longer issues API credentials, we actively discourage new Soundcite users from using SoundCloud for audio hosting. Thus, this is WONTFIX.
