### ISSUE TITLE
Design pass on created clips layout

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/soundcite#69]
![screen shot 2017-01-12 at 3 30 14 pm](https://cloud.githubusercontent.com/assets/741789/21909150/46955f90-d8dc-11e6-9778-6b0c375cb059.PNG)
delete button should be small and light like the buttons before it. Other tweaks need to be made to make the individual clips read better.

**Comment by JoeGermuska** [comment]
cleaning out the open issues. This seems moot since it hasn't come up in 5+ years.
