### ISSUE TITLE
Tips and Tricks needs written for orangeline update

### ISSUE THREAD

**Issue by yawkity** [NUKnightLab/soundcite#70]
We have placeholder text for tips and tricks on the orangeline version of the Soundcite website.

**Comment by JoeGermuska** [comment]
Here's a proposal. Fire away. @zachwise your feedback particularly requested.

![image](https://cloud.githubusercontent.com/assets/46313/22984968/ab0beba6-f36c-11e6-9e49-0ba13f895fc5.png)

**Comment by zachwise** [comment]
@JoeGermuska looks good to me.
