### ISSUE TITLE
Orangeline Authoring tool doesn't work

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/soundcite#73]
I was pretty sure I'd made this work, but it doesn't seem to.

Clicking on links in the "example" should fill the field in step 1 and act as though someone had clicked on "load".

Clicking on "load" should bring up a player for the given URL. And from there on, it should work just like it does on the current site.

**Comment by yawkity** [comment]
Seems to work for me

**Comment by JoeGermuska** [comment]
cleaning out the open issues. This seems to work fine.
