### ISSUE TITLE
i want embed code to iptv channel link

### ISSUE THREAD

**Issue by soou2** [NUKnightLab/soundcite#84]
i want embed code to iptv channel link
like this link http://51.255.76.200:8000/live/5Lvyprs736H7ho/JlRopPjP12owqQ/2617.ts
i want code to watch online

**Comment by JoeGermuska** [comment]
I'm not sure what IPTV is, but if the TV and "watch online" mean that it is video based, then this is out of scope for Soundcite, which has no UI for embedding video. We have no current plans to explore video.
