### ISSUE TITLE
Accessibility recommendations?

### ISSUE THREAD

**Issue by cmccullough012** [NUKnightLab/soundcite#86]
Hi, 

My team is using SoundCite for oral history clips embedded in narratives, but we want to make our site fully accessible to the deaf and hard-of-hearing people in our community. As it stands, SoundCite doesn't seem to have any smooth way to pop up transcripts or give the user the option to be redirected to a transcript. Also, there is no way to rewind the audio once it begins to play. Do you have suggestions on workarounds for this (most importantly, transcription), or any plans to implement these features? 

Thanks!

**Comment by JoeGermuska** [comment]
Thanks for your interest in SoundCite. We don't have any specific development plans for SoundCite at this time. Transcripts, especially, seem as though they would be out of scope given the design intention of an unobtrusive player which doesn't lead people out of the flow of the story.

You may want to look at AblePlayer, a media player explicitly designed for accessibility. They have [a demo of how it can work with transcripts](https://ableplayer.github.io/ableplayer/demos/audio4.html).

**Comment by cmccullough012** [comment]
Great, thank you so much!
