### ISSUE TITLE
About panel links to decommissioned website

### ISSUE THREAD

**Issue by sopel** [NUKnightLab/soundcite#95]
Deviating from your other great story telling tools, this repository's 'About' sidebar panel links to a seemingly decommissioned domain that is up for grabs rather than the nice existing [landing page](https://soundcite.knightlab.com/), compare:

### Actual
![image](https://user-images.githubusercontent.com/545193/123134048-ac698200-d450-11eb-853a-29b2bb9adba1.png)
### Desired

**https://soundcite.knightlab.com/**

**Comment by JoeGermuska** [comment]
Fixed; thanks for bringing this to our attention.
