### ISSUE TITLE
KnightLab to adjust for SoundCloud API update?

### ISSUE THREAD

**Issue by devonbussell** [NUKnightLab/soundcite#96]
I'm using Soundcite on an educational website, and my audio files are currently hosted on SoundCloud. My website is https://tfcs.baruch.cuny.edu/, and sample page where we're using Soundcite, for reference, is https://tfcs.baruch.cuny.edu/ks/

I recently received an email from SoundCloud informing me that recent changes to the SoundCloud API will start to effect API users beginning in September. We are actually in the process of moving our clips off of SoundCloud, but this will take some time - in the meantime, I’m wondering if Soundcite has any plans to patch the JS files to accommodate changes to the SoundCloud API.

I also posted this on the KnightLab ZenDesk forum - apologies for the duplication!

[Gmail - FW_ Action Required - Update your integration with SoundCloud API.pdf](https://github.com/NUKnightLab/soundcite/files/6938434/Gmail.-.FW_.Action.Required.-.Update.your.integration.with.SoundCloud.API.pdf)

**Comment by JoeGermuska** [comment]
Seeing this quite late, but responding not just for the original asker but also any who might find their way here.

These changes never affected SoundCite. However, as SoundCloud continues to decline to offer new API keys, we strongly recommend **against** anyone using SoundCloud to host audio for SoundCite. We've tried to make this more clear on the [SoundCite web page](https://soundcite.knightlab.com).
