### ISSUE TITLE
I'm trying to embed a soundcite clip in timelinejs sheet, but it isnt initializing, is there a way?

### ISSUE THREAD

**Issue by salus-sage** [NUKnightLab/soundcite#97]

**Comment by salus-sage** [comment]
I figured this out, leaving this issue for anyone else trying for similar use case. 
1. add the soundcite embed code in the timelinejs sheet, i've added in the text column
2. add soundcite css code in the header
3. you cant load the script before the timeline has loaded, thats what was my issue. so, timelinejs has a on loaded event, that's where i loaded the soundcite script. something like below,
``` js
timeline.on('loaded', function(event){
      var script = document.createElement('script');
      script.src = "https://cdn.knightlab.com/libs/soundcite/latest/js/soundcite.min.js";
      document.getElementsByTagName('head')[0].appendChild(script);
     });
```
This is how it looks,
![image](https://user-images.githubusercontent.com/6399323/144246512-a2d5412b-10b2-40ab-bf52-9e1e005755dd.png)

**Comment by JoeGermuska** [comment]
timelines hosted on Knight Lab's systems should not require any special handling. Timelines hosted externally which will include soundcite clips can simply set the `soundcite` option to `true` when the timeline is initialized and the TimelineJS code will handle loading soundcite and initializing clips.  This feature was added in version 3.7.6, released last August, although I realize as I write that it was not added to the [options documentation](http://timeline.knightlab.com/docs/options.html), which I will fix presently.
